on:
  workflow_dispatch:
    inputs:
      foo:
        description: "Foo"
        required: true
        type: choice
        options:
          - biz
          - boop
          - blur
      bar:
        if: ${{ github.event.inputs.foo }} == "boop"
        description: "Bar"
        required: false
        type: string


jobs:
  start-canary:
    # This job only runs for pull request comments
    name: Start Canary
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v3
      - name: Echo hey
        run: echo bonkers "$GITHUB_SHA" "${GITHUB_REF}" ${{ github.event.inputs.foo }} ${{ github.event.inputs.bar }}

