on:
  workflow_call:
    inputs:
      foo:
        description: "Foo"
        required: true
        type: choice
        options:
          - biz
          - boop
          - blur
      bar:
        description: "Bar"
        required: false
        type: string

env:
  FOO: ${{ inputs.foo }}
  BAR: ${{ inputs.bar }}

jobs:
  doSomething:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo $FOO && echo $BAR && echo $GITHUB_SHA && echo $GITHUB_REF && git log

